### ISSUE TITLE
Crash on Android 64bit builds

### ISSUE THREAD

**Issue by tomleavy** [markshiz/corefoundation-lite-android#2]
When running this library on a 64 bit android device you get a crash as soon as the library is loaded. When we comment out this line in CFInitialize everything seems to be ok:

https://github.com/markshiz/corefoundation-lite-android/blob/14d3c44ebb0d57efb5b94da2fb55e6d4d0f0a16b/jni/Base.subproj/CFRuntime.c#L637

**Comment by markshiz** [comment]
Yes, the version of CoreFoundation hosted here only covers 32-bit architecture --the project is quite old.  A newer version should need to be used to resolve this issue.
